//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Ripholes in Rubbish
//  @ File Name : WPad.h
//  @ Date : 1/24/2009
//  @ Author : 
//
//

#ifndef __WPAD_H__
#define __WPAD_H__

#include <PA9.h>

	bool AHeld()
   {
      return Pad.Held.A;
   }
	bool ANew()
   {
      return Pad.Newpress.A;
   }
	bool ARel()
   {
      return Pad.Released.A;
   }
   bool BHeld()
   {
      return Pad.Held.B;
   }
	bool BNew()
   {
      return Pad.Newpress.B;
   }
	bool BRel()
   {
      return Pad.Released.B;
   }
	bool XHeld()
   {
      return Pad.Held.X;
   }
	bool XNew()
   {
      return Pad.Newpress.X;
   }
	bool XRel()
   {
      return Pad.Released.X;
   }
	bool YHeld()
   {
      return Pad.Held.Y;
   }
	bool YNew()
   {
      return Pad.Newpress.Y;
   }
	bool YRel()
   {
      return Pad.Released.Y;
   }
	bool LSHeld()
   {
      return Pad.Held.L;
   }
	bool LSNew()
   {
      return Pad.Newpress.L;
   }
	bool LSRel()
   {
      return Pad.Released.L;
   }
	bool RSHeld()
   {
      return Pad.Held.R;
   }
	bool RSNew()
   {
      return Pad.Newpress.R;
   }
	bool RSRel()
   {
      return Pad.Released.R;
   }
	bool DLHeld()
   {
      return Pad.Held.Left;
   }
	bool DLNew()
   {
      return Pad.Newpress.Left;
   }
	bool DLRel()
   {
      return Pad.Released.Left;
   }
	bool DRHeld()
   {
      return Pad.Held.Right;
   }
	bool DRNew()
   {
      return Pad.Newpress.Right;
   }
	bool DRRel()
   {
      return Pad.Released.Right;
   }
	bool DUHeld()
   {
      return Pad.Held.Up;
   }
	bool DUNew()
   {
      return Pad.Newpress.Up;
   }
	bool DURel()
   {
      return Pad.Released.Up;
   }
	bool DDHeld()
   {
      return Pad.Held.Down;
   }
	bool DDNew()
   {
      return Pad.Newpress.Down;
   }
	bool DDRel()
   {
      return Pad.Released.Down;
   }
	bool StartNew()
   {
      return Pad.Newpress.Start;
   }
	bool SelectNew()
   {
      return Pad.Newpress.Select;
   }

#endif
