//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Ripholes in Rubbish
//  @ File Name : Player.cpp
//  @ Date : 1/31/2009
//  @ Author : 
//
//


#include "Player.h"

void Player::addObj() {

}

void Player::addHit() {

}

