//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Ripholes in Rubbish
//  @ File Name : Player.h
//  @ Date : 1/31/2009
//  @ Author : 
//
//


#if !defined(_PLAYER_H)
#define _PLAYER_H

#include "LevelObj.h"

class Player : public LevelObj {
public:
	Player(inPos,pid) : pos(inPos), pageId(pid) {
	xVel = 0;
	yVel = 0;
	objId = getSprite();
	isRippable = false;
	isFrozen = false;
	isHole = false;
    PA_CreateSprite(0, objId, (void*)mario_Sprite, OBJ_SIZE_32X32, 1, 0, pos.first, pos.second);
    spriteId++;
	hitbox = setHitBox("player");
	}


    ~Player();
private:
	u8 hitCount;
	void addHit();
};

#endif  //_PLAYER_H
